### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Popovkov57** [popovkov57/dikkenk-quotes#3]
Hi,

I need to:

- [ ] Improve style of the README
- [ ] Add instruction to install and run the program
- [ ] Add Licence

Thanks. Best regards

**Comment by Prakhar9450** [comment]
Please assign me this issue

**Comment by PratyayDhond** [comment]
I can do this, give me a bit more information about this in short

**Comment by PavvanPradeep** [comment]
can you assign this issue to me

**Comment by adarsh-kishore786** [comment]
For running this application, `nodejs` must be installed in the system, which can be downloaded from the official nodejs website. 

We also need to have the `npm` package `unique-random-array` which can be installed via
```
npm install unique-random-array
```

For testing on `src/index.test.js` we need to have the `jest` unit-testing package
```
npm install --save-dev jest
```
and make a change in `package.json`
```
"scripts": {
  "test": "jest"
}
```
Then, by running `npm test` we can do unit testing.

For including this application in any other program, we can `require` it and use its `random` function. For example
```
console.log(random(2));
```

This is what I have understood and if you assign this to me, then I can write it in README as instructions to install and run program.

**Comment by Popovkov57** [comment]
Hi @adarsh-kishore786 , @PratyayDhond , @PavvanPradeep and @Prakhar9450 

No need to assign the issue. It's open source. 

To contribute, see [this](https://github.com/firstcontributions/first-contributions).

Best regards.

**Comment by Popovkov57** [comment]
Issue closes. Thanks @adarsh-kishore786
