### ISSUE TITLE
Need to fix security vulnerability

### ISSUE THREAD

**Issue by Popovkov57** [popovkov57/dikkenk-quotes#5]

**Comment by PratyayDhond** [comment]
I could do it, but what security vulnerability exactly are we talking about here @Popovkov57

**Comment by Popovkov57** [comment]
Hi @PratyayDhond,

You can go [here](https://github.com/Popovkov57/Dikkenek-quotes/security/dependabot/1) to have some details.

Thanks

**Comment by BWsix** [comment]
> Hi @PratyayDhond,
> 
> You can go [here](https://github.com/Popovkov57/Dikkenek-quotes/security/dependabot/1) to have some details.
> 
> Thanks

The link you provided is only visible to you. (I would not make sense if anyone can see what vulnerabilities a project have, lol)

**Comment by PratyayDhond** [comment]
@Popovkov57 the link is inaccessible

**Comment by Popovkov57** [comment]
@PratyayDhond Thanks. The issue isn't accessible on public profil.

I take some print screen when i'm logged.

[printscreen 1](https://ibb.co/cxR0ZxP)

[printscreen2](https://ibb.co/DVFBB5z)

**Comment by Popovkov57** [comment]
I think it's not a good issue. I will see later to fix it. Thanks @PratyayDhond
