### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Popovkov57** [popovkov57/dikkenk-quotes#8]
- [ ] Add Contributors section
- [x] #14
- [ ] Add open source badge [![Open Source Love](https://firstcontributions.github.io/open-source-badges/badges/open-source-v1/open-source.svg)](https://github.com/firstcontributions/open-source-badges)
- [ ] Add discord badge [![Discord](https://badgen.net/badge/icon/discord?icon=discord&label)](https://discord.gg/RSutahprpy)

**Comment by ShubhamShakyawal** [comment]
@Popovkov57 Please assign me. I would like to work on this

**Comment by Popovkov57** [comment]
Hi @ShubhamShakyawal,

Don't need to assign you. Follow this [guideline](https://github.com/firstcontributions/first-contributions) to contribute. Thanks

Best regards.

**Comment by ShubhamShakyawal** [comment]
@Popovkov57 Updated the Readme file and Pull Request is made

https://github.com/Popovkov57/Dikkenek-quotes/pull/18
